name: Docker push

on:
  push:
    paths:
      - 'packages/slack-app'
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENCE"
      - "CODEOWNERS"
    branches:
      - releases/*

env:
  IMAGE_NAME: alvnoas/alvtime-slack-app-prod

jobs:
  push_to_docker_hub:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build ./packages/slack-app --tag $IMAGE_NAME:latest

      - uses: anchore/scan-action@master
        with:
          image-reference: $IMAGE_NAME:latest
          dockerfile-path: "./pacakges/slack-app/Dockerfile"
          fail-build: true
          include-app-packages: true

      - name: Anchore inline scan JSON results
        run: for j in `ls ./anchore-reports/*.json`; do echo "---- ${j} ----"; cat ${j}; echo; done

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push image
        run: docker push $IMAGE_NAME:latest
