[package]
name = "atime"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.42", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
sled = "1.0.0-alpha.124"
rustyline = { version = "17.0.2", features = ["derive"] }
reqwest = { version = "0.12", features = ["blocking", "json"] }
inquire = { version = "0.9.1" , features = ["date", "editor"]}
clap = { version = "4.5", features = ["derive"] }
clap_complete = "4.5"
tempfile = "3.23.0"
crossterm = "0.29.0"

[dev-dependencies]